version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: happy-schools-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/sql_app.db:/app/sql_app.db
      - ./backend/app:/app/app
      - ./backend/static:/app/static
    restart: always

  frontend:
    build:
      context: .
    container_name: happy-schools-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://<YOUR_VPS_IP>:8001
    depends_on:
      - backend
    restart: always
